[settings]
timeout = 1000


[relaychain]
default_image = "{{POLKADOT_IMAGE}}"
chain = "rococo-local"
command = "polkadot"

  [[relaychain.nodes]]
  name = "alice"
  args = [ "--alice", "-lruntime=debug,parachain=trace" ]

  [[relaychain.nodes]]
  name = "bob"
  args = [ "--bob", "-lruntime=debug,parachain=trace" ]

[[parachains]]
id = 2000
addToGenesis = false

  [parachains.collator]
  name = "regionx-collator01"
  image = "{{REGIONX_IMAGE}}"
  command = "regionx-node"
  args = [ "-lruntime=debug,parachain=trace" ]

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"
