name: Lint e2e_tests

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
        working-directory: ./e2e_tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - run: npm i
      - run: npm run format
      - run: npm run lint
      - run: npm run build
