name: Try-runtime

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  try-runtime:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - uses: ./.github/actions/setup

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.GH_TOKEN }}

    - name: Use Git CLI for Cargo
      run: echo "CARGO_NET_GIT_FETCH_WITH_CLI=true" >> $GITHUB_ENV

    - name: Try-Runtime Build
      run: cargo check --features try-runtime
